sudo: required

language: cpp

branches:
  only:
    - master
    - latest
    - release
    - coverity_scan

git:
  depth: 10

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9c376e047374d89cdeac
    on_success: always # default: always
    on_failure: always # default: always
    on_start: always   # default: never
    on_cancel: always # default: always
    on_error: always # default: always

env:
  global:
    # COVERITY_SCAN_TOKEN
    - secure: "o08nQFKhuSrBTX4FJO22YZ4h+igFq+Hgtz1bUW8wjKVNo83GTqJ2Z/gZfxSlxXBypJtz24Z14NsgCrb3XYrX
               wuMpTTsKK1SCzTHzmaf8BqZ1qJ9hYFtuX/Q8YInL1c27g5FUfvAWO1SlBAMOLuk+OqrX3lYb/yzf+3O1Ndvn\
               2JRMx5QaONUd7jTWs04VXZzvBpNfZOPU0ypKm6NEIvN/Wjak979iSLnW7O/HjpsOgdXEAzpIqb/xRaoDtrKP\
               IkPwoDbi2kbrZcw+/ile3iZ2m1l9MP4s79WDn/v1FtFBv+C4GI7ikXPG6qQ8J6yWyrOcnt1HZ9u+gdJ9E8rs\
               ZpMDSaR2rSB70rJMCGXzeG14dRUCzZsnumJ55+aY6rr/TDljOCOHQdHYofg0v6p82aojhtUo35EmedYbwkrI\
               c7E2QzfGuKL2qpBjsXFnXrTRRuwtY+XQI/YF6nGECHSD/3JQTEZv14ICPh6IiWF2fMqLvsxEBIk5sZahyBCy\
               Y1peQqb7CvxG4v1nNy3M9hS+k3L7Si541UpborI03sWgEUKWl9dBOxAwdYBaI6o4o+NvfpRbBY8rZLaEy+hK\
               n+UuglQBeunMB54dvZxpS7zbPkWgBrnhIWMz89Rx6DT97OsHJdgDNcUOPv1b6xRAQqs+Zd3+nZ2vQIkvZJU5\
               FwljLRWCfdg="

ref:
  sources: &sources
    - boost-latest
    - george-edison55-precise-backports
    - ubuntu-toolchain-r-test
  packages: &packages
    - cmake
    - cmake-data
    - g++-5
    - libboost-locale1.55-dev
    - libmyodbc
    - libsqliteodbc
    - mysql-client
    - odbc-postgresql
    - unixodbc
    - unixodbc-dev
  sqlite: &sqlite
    apt:
      sources: *sources
      packages: *packages
  mysql: &mysql
    mysql: "5.5"
    apt:
      sources: *sources
      packages: *packages
  postgresql: &postgresql
    postgresql: "9.1"
    apt:
      sources: *sources
      packages: *packages
  mariadb: &mariadb
    mariadb: "10.0"
    apt:
      sources: *sources
      packages: *packages
  vertica: &vertica
    apt:
      sources: *sources
      packages: *packages

matrix:
  include:
    - addons:
        apt:
          sources: *sources
          packages: *packages
        # The single build job that submits the Coverity Scan file
        coverity_scan:
          project:
            name: "lexicalunit/nanodbc"
            description: "A small C++ wrapper for ODBC"
          notification_email: mateusz@loskot.net
          build_command_prepend: mkdir -p build.coverity && pushd build.coverity && cmake -DCMAKE_BUILD_TYPE=Debug .. && popd
          build_command: cmake --build ./build.coverity
          branch_pattern: coverity_scan
      compiler: gcc
      env: DB=sqlite COVERITY=ON DISABLE_LIBCXX=ON DISABLE_EXAMPLES=OFF
      os: linux
    - addons: *sqlite
      compiler: gcc
      env: DB=sqlite BUILD_SHARED_LIBS=ON DISABLE_LIBCXX=ON
      os: linux
    - addons: *sqlite
      compiler: gcc
      env: DB=sqlite ENABLE_BOOST=ON DISABLE_LIBCXX=ON
      os: linux
    - addons: *mysql
      compiler: gcc
      env: DB=mysql DISABLE_LIBCXX=ON
      os: linux
    - addons: *mysql
      compiler: gcc
      env: DB=mysql ENABLE_BOOST=ON DISABLE_LIBCXX=ON
      os: linux
    - addons: *mysql
      compiler: gcc
      env: DB=mysql ENABLE_UNICODE=ON DISABLE_LIBCXX=ON DISABLE_EXAMPLES=OFF
      os: linux
    - addons: *mysql
      compiler: gcc
      env: DB=mysql ENABLE_UNICODE=ON ENABLE_BOOST=ON DISABLE_LIBCXX=ON DISABLE_EXAMPLES=OFF
      os: linux
    - addons: *postgresql
      compiler: gcc
      env: DB=postgresql DISABLE_LIBCXX=ON
      os: linux
    - addons: *mariadb
      compiler: gcc
      env: DB=mariadb DISABLE_LIBCXX=ON
      os: linux
    - addons: *vertica
      compiler: gcc
      env: DB=vertica DISABLE_LIBCXX=ON
      os: linux
    - compiler: clang
      env: DB=sqlite
      os: osx
    - compiler: clang
      env: DB=sqlite ENABLE_BOOST=ON
      os: osx
  allow_failures:
    - env: DB=mariadb DISABLE_LIBCXX=ON

# before_install runs after matrix.addons.apt installation targets in the matrix
before_install:
  # Skip build if the commit message contains [skip travis] or [travis skip]
  # https://github.com/travis-ci/travis-ci/issues/5032
  - >
      echo "$TRAVIS_COMMIT_MESSAGE" | grep -E  '\[(skip travis|travis skip)\]'
      && echo "[skip travis] has been found, exiting."
      && exit 0 || true
  - ${TRAVIS_BUILD_DIR}/utility/ci/travis/before_install.$TRAVIS_OS_NAME.sh
  - ${TRAVIS_BUILD_DIR}/utility/ci/travis/before_install.vertica.sh

before_script:
  - source "${TRAVIS_BUILD_DIR}/utility/ci/travis/before_script.$DB.sh"
  - if [[ -f /etc/odbcinst.ini ]]; then export ODBCSYSINI=/etc; fi
  - if [[ -f /etc/odbc.ini ]]; then export ODBCINI=/etc/odbc.ini; fi
  - odbcinst -j
  - if [[ -f "$ODBCSYSINI/odbcinst.ini" ]]; then odbcinst -q -d; fi
  - if [[ -s "$ODBCINI" ]]; then odbcinst -q -s; fi

script:
  - ${TRAVIS_BUILD_DIR}/utility/ci/travis/script.sh
