version: 1.0.{build}

os: Visual Studio 2015

platform: x64

configuration: Release

branches:
  only:
    - master
    - latest
    - release

shallow_clone: true
clone_depth: 5

environment:
  matrix:
    - DB: SQLite
      GENERATOR: "Visual Studio 14 2015"
      USE_UNICODE: OFF
      USE_BOOST_CONVERT: OFF
    - DB: SQLite
      GENERATOR: "Visual Studio 14 2015 Win64"
      USE_UNICODE: OFF
      USE_BOOST_CONVERT: OFF
    - DB: SQLite
      GENERATOR: "NMake Makefiles"
      PLATFORM: x86-32
      USE_UNICODE: OFF
      USE_BOOST_CONVERT: OFF
      DISABLE_ASYNC: ON
    - DB: MSSQL2016
      GENERATOR: "Visual Studio 14 2015 Win64"
      USE_UNICODE: OFF
      USE_BOOST_CONVERT: OFF
    - DB: MSSQL2016
      GENERATOR: "Visual Studio 14 2015 Win64"
      USE_UNICODE: ON
      USE_BOOST_CONVERT: OFF
    - DB: MSSQL2014
      GENERATOR: "Visual Studio 14 2015 Win64"
      USE_UNICODE: OFF
      USE_BOOST_CONVERT: OFF
    - DB: MSSQL2008
      GENERATOR: "Visual Studio 14 2015 Win64"
      USE_UNICODE: OFF
      USE_BOOST_CONVERT: OFF
    - DB: MySQL
      GENERATOR: "Visual Studio 14 2015 Win64"
      USE_UNICODE: OFF
      USE_BOOST_CONVERT: OFF
    - DB: PostgreSQL
      GENERATOR: "Visual Studio 14 2015 Win64"
      USE_UNICODE: OFF
      USE_BOOST_CONVERT: OFF
    - DB: SQLite
      GENERATOR: "MinGW Makefiles"
      PLATFORM: x86-32
      USE_UNICODE: OFF
      USE_BOOST_CONVERT: OFF
      DISABLE_ASYNC: ON
    - DB: SQLite
      GENERATOR: "MinGW Makefiles"
      PLATFORM: x86-64
      USE_UNICODE: OFF
      USE_BOOST_CONVERT: OFF
      DISABLE_ASYNC: ON

matrix:
  allow_failures:
    - GENERATOR: "MinGW Makefiles"
      PLATFORM: x86-32

init:
  # For MinGW make to work correctly sh.exe must NOT be in your path.
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - ps: |
      Write-Host "Build worker environment variables:" -ForegroundColor Magenta
      Get-ChildItem Env: | %{"{0}={1}" -f $_.Name,$_.Value}
  - if "%GENERATOR%"=="NMake Makefiles" if "%PLATFORM%"=="x86-32" call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
  - if "%GENERATOR%"=="NMake Makefiles" if "%PLATFORM%"=="x86-64" "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64

install:
  - ps: |
      if ($env:DB -Match "SQLite") {
        Write-Host "Installing SQLite ODBC Driver:" -ForegroundColor Magenta
        $sqliteodbc64Path = "$($env:TEMP)\sqliteodbc_w64.exe"
        $sqliteodbc32Path = "$($env:TEMP)\sqliteodbc.exe"
        (New-Object Net.WebClient).DownloadFile('http://www.ch-werner.de/sqliteodbc/sqliteodbc_w64.exe', $sqliteodbc64Path)
        (New-Object Net.WebClient).DownloadFile('http://www.ch-werner.de/sqliteodbc/sqliteodbc.exe', $sqliteodbc32Path)
        cmd /c start /wait $sqliteodbc64Path /S
        if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
        cmd /c start /wait $sqliteodbc32Path /S
        if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
       }
  - ps: |
      Write-Host "Installed ODBC drivers:" -ForegroundColor Magenta
      Get-OdbcDriver -Platform 64-bit | Select-Object -ExpandProperty Name
  - ps: |
      if ($env:GENERATOR -Match "MinGW") {
        if ($env:PLATFORM -Match "x86-32") {
          $env:Path += ";C:\MinGW\bin"
        } else {
          $env:Path += ";C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin"
        }
        g++ --version
      }

before_build:
  - ps: 'Write-Host "Running cmake:" -ForegroundColor Magenta'
  - cmake.exe -G "%GENERATOR%" -DCMAKE_BUILD_TYPE=Release -DNANODBC_USE_BOOST_CONVERT=%USE_BOOST_CONVERT% -DNANODBC_USE_UNICODE=%USE_UNICODE% -DNANODBC_DISABLE_ASYNC=%DISABLE_ASYNC% -DNANODBC_STATIC=ON -DNANODBC_HANDLE_NODATA_BUG=OFF -DNANODBC_INSTALL=OFF %APPVEYOR_BUILD_FOLDER%

build_script:
  - ps: 'Write-Host "Running cmake --build:" -ForegroundColor Magenta'
  - cmake --build . --config Release

before_test:
  - ps: 'Write-Host Configuring $env:DB service -ForegroundColor Magenta'
  - ps: |
      if ($env:DB -Match "MSSQL2008") {
        Start-Service 'MSSQL$SQL2008R2SP2'
      } elseif ($env:DB -Match "MSSQL2014") {
        Start-Service 'MSSQL$SQL2014'
      } elseif ($env:DB -Match "MSSQL2016") {
        Start-Service 'MSSQL$SQL2016'
      } elseif ($env:DB -Match "MySQL") {
        Start-Service MySQL57
        $env:MYSQL_PWD="Password12!"
        $cmd = '"C:\Program Files\MySQL\MySQL Server 5.7\bin\mysql" -e "create database nanodbc_test;" --user=root'
        iex "& $cmd"
      } elseif ($env:DB -Match "PostgreSQL") {
        Start-Service postgresql-x64-9.5
        $env:PGUSER="postgres"
        $env:PGPASSWORD="Password12!"
        $cmd = '"C:\Program Files\PostgreSQL\9.3\bin\createdb" nanodbc_test'
        iex "& $cmd"
      }
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }

test_script:
  - ps: |
      if ($env:DB -Match "MSSQL2008") {
        $env:NANODBC_TEST_CONNSTR_MSSQL="Driver={ODBC Driver 11 for SQL Server};Server=(local)\SQL2008R2SP2;Database=master;UID=sa;PWD=Password12!;"
        $test_name = "mssql_test"
      } elseif ($env:DB -Match "MSSQL2014") {
        $env:NANODBC_TEST_CONNSTR_MSSQL="Driver={ODBC Driver 11 for SQL Server};Server=(local)\SQL2014;Database=master;UID=sa;PWD=Password12!;"
        $test_name = "mssql_test"
      } elseif ($env:DB -Match "MSSQL2016") {
        $env:NANODBC_TEST_CONNSTR_MSSQL="Driver={ODBC Driver 11 for SQL Server};Server=(local)\SQL2016;Database=master;UID=sa;PWD=Password12!;"
        $test_name = "mssql_test"
      } elseif ($env:DB -Match "MySQL") {
        $env:NANODBC_TEST_CONNSTR_MYSQL="Driver={MySQL ODBC 5.3 ANSI Driver};Server=127.0.0.1;Database=nanodbc_test;User=root;Password=Password12!;big_packets=1;"
        $test_name = "mysql_test"
      } elseif ($env:DB -Match "PostgreSQL") {
        $env:NANODBC_TEST_CONNSTR_PGSQL="Driver={PostgreSQL ANSI(x64)};Server=127.0.0.1;Port=5432;Database=nanodbc_test;Uid=postgres;Pwd=Password12!;"
        $test_name = "postgresql_test"
      } elseif ($env:DB -Match "SQLite") {
        $test_name = "sqlite_test"
      } else {
        throw 'TODO: ' + $env:DB + ' not configured yet'
      }
      Write-Host Running $Env:CONFIGURATION build test: $test_name -ForegroundColor Magenta
  - ps: |
      $cmd = 'ctest -V --output-on-failure -C ' + $Env:CONFIGURATION + ' -R ' + $test_name
      iex "& $cmd"
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }

# If you need to debug AppVeyor session (https://www.appveyor.com/docs/how-to/rdp-to-build-worker), then:
# 1. Uncomment the on_finish section below:
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
# 2. Add this line to the init section below
#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
